# Chapter 1 - Tokenization and Bag of Words

## 1.1 Tokenization

### Step 1 - The corpus

We have 3 customer reviews and we want to know which 2 are similar

In [3]:
docs = [
    "the discount was reduced",
    "we lowered our pricing",
    "the customer filed a complaint"
]
for d in docs:
    print(d)

the discount was reduced
we lowered our pricing
the customer filed a complaint


**Corpus** - full collection of text we're working with

### Step 2 - Tokenization

In [4]:
for d in docs:
    print(d.split())

['the', 'discount', 'was', 'reduced']
['we', 'lowered', 'our', 'pricing']
['the', 'customer', 'filed', 'a', 'complaint']


Splitting text into words is called **tokenization** and each unit is a token

### Step 3 - Vocabulary

In [5]:
vocab = sorted({w for d in docs for w in d.split()})
print(vocab)

['a', 'complaint', 'customer', 'discount', 'filed', 'lowered', 'our', 'pricing', 'reduced', 'the', 'was', 'we']


In [6]:
word_to_idx = {w: i for i, w in enumerate(vocab)}
print(word_to_idx)

{'a': 0, 'complaint': 1, 'customer': 2, 'discount': 3, 'filed': 4, 'lowered': 5, 'our': 6, 'pricing': 7, 'reduced': 8, 'the': 9, 'was': 10, 'we': 11}


### Step 4 - Bag of words

Now the document became 12 number, which makes the document comparable!!!

In [8]:
import numpy as np

v = np.zeros(len(vocab))
print(v)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
doc = docs[0]

for w in doc.split():
    idx = word_to_idx[w]
    v[idx] += 1
    print(w," -> index", idx)

print(v)

the  -> index 9
discount  -> index 3
was  -> index 10
reduced  -> index 8
[0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 1. 0.]


In [10]:
def bag_of_words(doc, vocab, word_to_idx):
    v = np.zeros(len(vocab))
    for w in doc.split():
        if w in word_to_idx:
            v[word_to_idx[w]] += 1
    return v

In [11]:
X = np.array([bag_of_words(d, vocab, word_to_idx) for d in docs])
print(X)
print(X.shape)

[[0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1.]
 [1. 1. 1. 0. 1. 0. 0. 0. 0. 1. 0. 0.]]
(3, 12)


**document-term matrix** - rows are documents and columns are terms.
 
In each row, most of it is zero -> **sparcity**

In [12]:
docs2 = docs + ["the discount policy was the best discount"]

vocab2 = sorted({w for d in docs2 for w in d.split()})
word_to_idx2 = {w: i for i, w in enumerate(vocab2)}

In [15]:
X2 = np.array([bag_of_words(d, vocab2, word_to_idx2) for d in docs2])
X2

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1.],
       [1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 2., 0., 0., 0., 1., 0., 0., 2., 1., 0.]])

In [14]:
import pandas as pd
pd.DataFrame(X2, columns=vocab2, index = ["doc1", "doc2", "doc3", "doc4"])

,a,best,complaint,customer,discount,filed,lowered,our,policy,pricing,reduced,the,was,we
doc1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0
doc2,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
doc3,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
doc4,0.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,1.0,0.0
